# Generated by Django 5.0.3 on 2024-03-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipelists_recipes_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
    ]
